[package]
name = "df-pn"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
once_cell = "1.19.0"
rocksdb = "0.22.0"
