[package]
name = "df-pn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = { version = "0.9.12", features = ["autocomplete", "derive"] }
colored = "2.1.0"
once_cell = "1.19.0"
